# This is a basic workflow to help you get started with Actions

name: Run models

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pygad
          pip install pandas
      - name: Run Models
        run: |
          ls -l
          python run_all.py > results.csv
          ls -l
          git remove -v
        working-directory: ./
      - name: switch from HTTPS to SSH
        run: git remote set-url origin git@github.com:Old-Shatterhand/Splits.git
      - name: Stage results
        run: git add results.*
      - name: commit results
        run: git commit -m "Auto-upload of results"
      - name: fetch from master
        run: git fetch origin main
      - name: push results to main
        run: git push origin HEAD:master
