# This is a basic workflow to help you get started with Actions

name: Run models

# Controls when the workflow will run
on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install pygad
          pip install pandas
      - name: Run Models
        run: |
          ls -l
          python run_all.py > results.csv
          ls -l
          git remote -v
        working-directory: ./
      - name: switch from HTTPS to SSH
        run: |
          git remote set-url origin git@github.com:Old-Shatterhand/Splits.git
      - name: Stage results
        run: |
          git add results.*
      - name: commit results
        run: |
          git config user.email "joeres.roman@web.de"
          git config user.name "Old-Shatterhand"
          git commit -m "Auto-upload of results"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github-tokan: ${{ secrets.GITHUB_TOKEN }}
